import type { Metadata } from "next";
import "./globals.css";
import '@radix-ui/themes/styles.css';
import { Theme } from '@radix-ui/themes';
import Page from "./page";
import { cookies } from 'next/headers'


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies()
console.log(cookieStore.getAll())
  return (
      <html lang="en">
        <body>
          <Theme>
            <Page />
          </Theme>
        </body>
      </html>
  )
}
